
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: development_toy

test:
  <<: *default
  database: test_toy

production:
  <<: *default
  database: production_toy
